### ISSUE TITLE
seqs.Mapx doesn't return error properly

### ISSUE THREAD

**Issue by illiaizotov-dev** [bobg/seqs#2] opened 2024-10-03 23:00 UTC
Thank you for your amazing library.

Can you please confirm that this code should properly return the error?

```
package main

import (
	"errors"
	"github.com/bobg/seqs"
	"slices"
)

func main() {
	a := []int{1, 2, 3}
	_, err := seqs.Mapx(slices.Values(a), func(i int) (int, error) {
		return 0, errors.New("error")
	})

	if *err != nil {
		println("error")
	} else {
		println("result")
	}
}
```

Instead I'm getting "result" printed out in the console.

**Comment by bobg** [comment] 2024-10-04 03:28
This is working as intended. The error pointer returned from `Mapx` (and a number of other functions in this package) - which, by the way, I recommend assigning to a variable named `errptr` rather than `err` - should be dereferenced and checked only _after_ the iterator has been consumed.

In the example above, you've created a new iterator with `Mapx` but discarded it. As such, you're never producing any elements for the new iterator, and the `func` you passed to `Mapx` is never getting called.

Try this instead:

```go
mapped, errptr := seqs.Mapx(slices.Values(a), func(int) (int, error) {
  return 0, errors.New("error")
})
for range mapped { /* this consumes the contents of the iterator */ }
if *errptr != nil {
  println("error")
} else {
  println("result"}
}
```

**Closed as completed by bobg** 2024-10-04 03:28 UTC

**Comment by bobg** [comment] 2024-10-05 15:36
By the way, please note that even in the example I gave above, you still won't get an error if `a` is an empty slice. There again, the `func` never gets called.
